README.md
Updated README with project description provided in SDP proposal
=> Updated README with project description provided in SDP proposal

app/src/main/java/ch/epfl/sdp/appart/user/User.java
addresses issue #20 
All methods in this class are mandatory to implement for every user.
**note** - the Object type was chosen for the getProfileImage() getter, should be changed once the object Picture is identified.
=> added general User interface

app/src/main/java/ch/epfl/sdp/appart/user/UniversityEmailDatabase.java, app/src/test/java/ch/epfl/sdp/appart/AppUserTest.java, app/src/test/java/ch/epfl/sdp/appart/UniversityEmailDatabaseTest.java
Fixes and tests for issue #20
+ This commit includes **two JUnit test classes** for AppUser and UniversityEmailDatabase.
+ Also a new static method **emailSyntaxIsValid()** was added to UniversityEmailDatabase to check the syntax validity of an email address.
=> Email syntax verification and tests for AppUser and UniversityEmailDatabase

.idea/codeStyles/Project.xml, app/build.gradle, app/src/androidTest/java/ch/epfl/sdp/appart/LoginUITest.java, app/src/main/AndroidManifest.xml, app/src/main/java/ch/epfl/sdp/appart/MainActivity.java, app/src/main/java/ch/epfl/sdp/appart/user/LoginActivity.java, app/src/main/java/ch/epfl/sdp/appart/user/ResetActivity.java, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_reset.xml, app/src/main/res/values-round/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, build.gradle
Added two activities, one for the login view and the other for the forgotten password view
=> added login ui and tests for it

app/src/main/java/ch/epfl/sdp/appart/login/FirebaseLoginService.java, app/src/main/java/ch/epfl/sdp/appart/user/AppUser.java, app/src/main/java/ch/epfl/sdp/appart/user/Gender.java, app/src/main/java/ch/epfl/sdp/appart/user/User.java, app/src/test/java/ch/epfl/sdp/appart/AppUserTest.java
This commit contains
-----------------------------------------------------------------------------------------------------------------------------
+ Updated **User interface** which matches new architecture
+ Updated **AppUser** class 
+ Updated **AppUser** test class to test new attributes
+ **Gender enum** - used in user interface gender of a user has a small fixed number of possibilities thus should be stored as an enum (not a string)
+ Quick fix in FirebaseLoginService (just for compiling purposes - AppUser now has a different constructor)
=> updated User interface and AppUser class to match new architecture

summaries/sprint2.md
Summary file for sprint 2.
As per usual please fill it out asap, and @Hbju is in charge of the overall team part.
=> Summary sprint 2

app/src/androidTest/java/ch/epfl/sdp/appart/LoginTest.java, app/src/main/java/ch/epfl/sdp/appart/login/FirebaseLoginService.java
related to #90 and bringing a solution to the problem as described in the issue.
This PR ensure a sign out on the Firebase login service creation.
=> Hot fix firebaselogin 

app/src/main/java/ch/epfl/sdp/appart/database/FirestoreDatabaseService.java, app/src/main/java/ch/epfl/sdp/appart/database/firestorelayout/AdLayout.java, app/src/main/java/ch/epfl/sdp/appart/database/firestorelayout/CardLayout.java, app/src/main/java/ch/epfl/sdp/appart/database/firestorelayout/UserLayout.java
This PR fulfills the issue #114. It replaced the fields used to access the database by our conventions.
=> modified the firebase fields

app/src/main/res/layout/panoramagl.xml
This PR is aiming to fix the back button on panorama activity that fail sometime.
=> Fix back button bug 

app/src/main/res/layout/panoramagl.xml
This PR tries to fix the back button again.
=> Second attempt to fix the back button problem.

app/src/main/java/ch/epfl/sdp/appart/PanoramaActivity.java, app/src/main/java/ch/epfl/sdp/appart/glide/visitor/GlideBitmapLoader.java
This PR aim to fix the memory recycling problem when loading bitmaps.
=> fixed the potential memory problem with panorama loading

app/src/main/res/layout/card_layout.xml
Little fix to show npa and city name
=> Card layout fix on city name

app/src/androidTest/java/ch/epfl/sdp/appart/DatabaseTest.java, app/src/androidTest/java/ch/epfl/sdp/appart/ScrollingUITest.java, app/src/main/java/ch/epfl/sdp/appart/ScrollingActivity.java, app/src/main/java/ch/epfl/sdp/appart/database/DatabaseService.java, app/src/main/java/ch/epfl/sdp/appart/database/FirestoreDatabaseService.java, app/src/main/java/ch/epfl/sdp/appart/database/FirestoreEmulatorDatabaseServiceWrapper.java, app/src/main/java/ch/epfl/sdp/appart/database/MockDatabaseService.java, app/src/main/java/ch/epfl/sdp/appart/scrolling/ScrollingViewModel.java, app/src/main/res/layout/activity_scrolling.xml, app/src/main/res/values/strings.xml, app/src/test/java/ch/epfl/sdp/appart/MockDatabaseTest.java
This PR refer to issue #164.
I update the scrolling activity with a search bar and ad a function in the database to filter the cards by location.
https://user-images.githubusercontent.com/36636060/116378488-78882c80-a812-11eb-8af9-8d4b65dbf376.mov
=> Implement search bar 

app/src/androidTest/java/ch/epfl/sdp/appart/PictureImportUITest.java, app/src/main/AndroidManifest.xml, app/src/main/java/ch/epfl/sdp/appart/AdCreationActivity.java, app/src/main/java/ch/epfl/sdp/appart/MainActivity.java, app/src/main/java/ch/epfl/sdp/appart/PicturesImportActivity.java, app/src/main/java/ch/epfl/sdp/appart/ad/AdCreationViewModel.java, app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreAdHelper.java, app/src/main/java/ch/epfl/sdp/appart/panorama/PictureCardAdapter.java, app/src/main/res/layout/activity_adcreation.xml
This PR partially address #128. It add the ability to see the images added in the ad creation and to see the pictures added in the virtual tour creation. Basically this PR add UI.
=> Feature images import in ad creation activity

app/src/main/java/ch/epfl/sdp/appart/PanoramaActivity.java
This PR add to our app the use of the sensor in the panorama activity.
=> Enabling accelerometer to the app

app/src/androidTest/java/ch/epfl/sdp/appart/ScrollingUITest.java, app/src/main/res/menu/actions_toolbar.xml, app/src/main/res/menu/ad_toolbar.xml
This PR addresses #257 . It removes the settings tab from the toolbar.
=> Remove settings tab from toolbar

app/src/main/java/ch/epfl/sdp/appart/AdActivity.java, app/src/main/java/ch/epfl/sdp/appart/ad/AdViewModel.java
This PR aims at fixing what is suggested by the title. I left a comment in the code where I explain why I chose to set hasVTour to be : panoramaReferences.size() > 0. What do you think ?
=> Fix crash when clicking on the panorama button and the ad has no VTour

app/src/androidTest/java/ch/epfl/sdp/appart/userui/UserProfileActivityTest.java, app/src/main/java/ch/epfl/sdp/appart/LoginActivity.java, app/src/main/java/ch/epfl/sdp/appart/database/local/MockLocalDatabase.java, app/src/test/java/ch/epfl/sdp/appart/MockLocalDatabaseTest.java
When the user logged in the "normal" way, that is to say without using the shared preferences, the user data was not saved to the local db.
=> Fix user not being save to the local database.

app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationVMTest.java, app/src/main/java/ch/epfl/sdp/appart/AdActivity.java, app/src/main/java/ch/epfl/sdp/appart/AdCreationActivity.java, app/src/main/java/ch/epfl/sdp/appart/FavoriteActivity.java, app/src/main/java/ch/epfl/sdp/appart/MapActivity.java, app/src/main/java/ch/epfl/sdp/appart/PlaceActivity.java, app/src/main/java/ch/epfl/sdp/appart/ad/AdCreationViewModel.java, app/src/main/java/ch/epfl/sdp/appart/ad/UserAdsViewModel.java, app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreAdHelper.java, app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreCardHelper.java, app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreUserHelper.java, app/src/main/java/ch/epfl/sdp/appart/database/local/LocalAdReader.java, app/src/main/java/ch/epfl/sdp/appart/login/FirebaseLoginService.java, app/src/main/java/ch/epfl/sdp/appart/map/helper/MapFrontendHelper.java, app/src/main/java/ch/epfl/sdp/appart/panorama/PictureCardAdapter.java, app/src/main/java/ch/epfl/sdp/appart/scrolling/ScrollingViewModel.java, app/src/main/java/ch/epfl/sdp/appart/user/UserViewModel.java, app/src/main/java/ch/epfl/sdp/appart/utils/DatabaseSync.java
Checking correct use of completable futures throughout the whole project.
**ISSUES**
- we used a (sadly) balanced mix of Void and Boolean futures. Completely switching to one or the other would be a risk since the deadline is so close. I just checked that the futures are completed both normally and exceptionally, and that the result is correctly used.
=> CompletableFuture checks

app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationDemoUITest.java, app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationUITest.java, app/src/main/java/ch/epfl/sdp/appart/AdCreationActivity.java, app/src/main/java/ch/epfl/sdp/appart/ad/AdCreationViewModel.java, app/src/main/res/values/strings.xml
This PR refer to the issue #249. Now when a user put a wrong location a toast is display and you are forced to change the address!
=> display an error if the locality isn't good
